# Numerical Python (NumPy) 

NumPy is the fundamental package for scientific computing with Python. The main benefit of Numpy is its powerful N-dimensional array object that it provides.

An array is collection of items stored at contiguous memory locations. The idea is to store multiple items of same type together.

https://numpy.org/

In [1]:
import numpy as np

In [2]:
my_list=[1,2,3]
n=np.array(my_list)
n

array([1, 2, 3])

In [3]:
type(my_list)

list

In [4]:
np.array([1,2,3])

array([1, 2, 3])

# creating multi-dimensional Array

In [5]:
list_of_list=np.array([[1,2,3],[4,5,6],[7,8,9]])
list_of_list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
list_of_list.shape

(3, 3)

In [7]:
np.arange(0,10)  #start from zero, generate 10 numbers. NB: the last digit will not appear

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(10)   #numpy will be intelligent to generate 10 numbers excluding the last digit

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)    #generating numbers from 0 to 10 in an interval of 2

array([0, 2, 4, 6, 8])

In [10]:
zero=np.zeros(100)

In [11]:
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
one=np.ones((3,3))

In [13]:
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
one=np.ones(10)
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
mn=np.arange(0,50,2)
mn

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [16]:
len(mn)

25

In [17]:
mn.reshape(5,5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [18]:
o=np.linspace(0,7,10)
o

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [19]:
len(o)

10

In [20]:
o.resize(5,2)  #Permently change 

In [21]:
o

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

In [22]:
o.reshape(2,5)   #Temporarily change

array([[0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111],
       [3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ]])

In [23]:
o

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

# Generate some random values

In [24]:
np.random.rand(3,2)   #Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).

array([[0.26470788, 0.94080682],
       [0.58588426, 0.80160454],
       [0.52696071, 0.79031998]])

In [25]:
a=np.random.randn(3,3)  #Return a sample (or samples) from the “standard normal” distribution.
a

array([[ 0.61733299,  1.3458375 ,  0.00191367],
       [-0.26299915, -0.47466821,  0.47088068],
       [ 0.34502375,  0.90055665,  0.59563147]])

In [26]:
#generating 10 numbers between 4 to 15
b=np.random.randint(4,15,10)  #Return random integers from low (inclusive) to high (exclusive).
b

array([ 6,  7, 10,  9,  8,  9,  4, 11, 11,  6])

In [27]:
b.reshape(5,2)

array([[ 6,  7],
       [10,  9],
       [ 8,  9],
       [ 4, 11],
       [11,  6]])

In [28]:
tt=np.random.randint(4,15,(4,3))
tt

array([[ 9,  6, 12],
       [ 5, 13, 14],
       [10, 14, 12],
       [13, 10,  7]])

# Indexing and Slicing

In [29]:
mm=np.random.randint(4,15,10)
mm

array([ 8, 12, 12, 14, 12,  6,  9,  5,  4,  9])

In [30]:
mm[1]

12

In [31]:
mm[-1]

9

In [32]:
mm[0]

8

In [33]:
mm[3:7]

array([14, 12,  6,  9])

In [34]:
mm[3:]

array([14, 12,  6,  9,  5,  4,  9])

In [35]:
mm[5:-2]

array([6, 9, 5])

In [37]:
mm.resize(2,5)

In [38]:
mn=np.arange(36)

In [39]:
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [40]:
mn.resize(6,6)

In [41]:
mn

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [42]:
mn[2,3]

15

In [44]:
mn[4, 2:5] #use : to select a range of rows or columns

array([26, 27, 28])

In [45]:
mn[2:]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [46]:
mn[3::,3:]

array([[21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])

In [48]:
mn[mn>25]   # conditional indexing

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [50]:
mn[mn > 25]=25   #casting all the values that are greater than 25 to 25
mn

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25]])

In [51]:
mn[1:,4]

array([10, 16, 22, 25, 25])

### Creating Copy

In [52]:
mn1=mn[3:,3:]

In [53]:
mn1

array([[21, 22, 23],
       [25, 25, 25],
       [25, 25, 25]])

In [54]:
mn_copy=mn.copy()

In [55]:
mn_copy

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25]])

In [56]:
mn_copy[mn_copy>5]=5 #broadcast all the numbers greater than 5 as 5
mn_copy

array([[0, 1, 2, 3, 4, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [57]:
mn

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25]])